### PR TITLE
Timebase

### LINKED ISSUE #1956: [macOS / M1] cpu_percent() gives incorrect information
## Summary

* OS: macOS 11.4
* Architecture: ARM
* Psutil version: 5.8.0
* Python version: 3.9.4
* Type: core

## Description

Process.cpu_percent() always reports very low cpu usage, in contradiction to top and Activity monitor. This test program:

```
from concurrent.futures import ThreadPoolExecutor
import psutil
import time
from math import log

def work(n):
    m = 0
    for i in range(1, n**2):
        m += log(i)
    return True
    
executor = ThreadPoolExecutor(max_workers=2)
task = executor.submit(work, 10000)

proc = psutil.Process()
while not task.done():
    print(proc.cpu_percent(interval=1))
```

consistently reports 2.4% usage on the Mac (vs. ~100% usage, as expected, on linux with the same version of psutil).

### PR DESCRIPTION
**Pull request by odormond**
## Summary

* OS: macOS 12.0.1, 11.6.1
* Bug fix: yes
* Type: core
* Fixes: #1956

## Description

Mach sys calls report cpu time in "tick units" -- on intel cpus, these happen to be nsecs but on M1 machines they're about 40 nsecs. This PR corrects for this, but I think it still needs two improvements: the value of mach_timebase_info should be cached somewhere, and there are probably other places where the code depends on 1 tick=1 nsec that also need to be updated. Sounds reasonable? I can work on both of those, but I wanted to get some feedback first before I spend any more time on this.

Based on @rmalouf PR #1958.

### CODE REVIEW

**Comment by giampaolo** [comment]
>  the value of mach_timebase_info should be cached somewhere

Makes sense. You can do that in `psutil_setup()` function, which is called on module init:
https://github.com/giampaolo/psutil/blob/8fa1746685a86b8ddda454e2e2746d535e2b6d89/psutil/_psutil_common.c#L395
You should define the new global var as a C `extern` defined in `_psutil_common.h`.  grep for `PSUTIL_SYSTEM_INFO` to see how it's done.

File: psutil/_psutil_osx.c [hunk 1]
```diff
@@ -279,16 +280,24 @@ static PyObject *
...
+    total_user /= info.denom;
+    total_system = pti.pti_total_system * info.numer;
+    total_system /= info.denom;
+
     return Py_BuildValue(
         "(ddKKkkkk)",
-        (float)pti.pti_total_user / 1000000000.0,     // (float) cpu user time
-        (float)pti.pti_total_system / 1000000000.0,   // (float) cpu sys time
+        (float)total_user / 1000000000.0,     // (float) cpu user time
+        (float)total_system / 1000000000.0,   // (float) cpu sys time
```
Comment (giampaolo) [inline psutil/_psutil_osx.c:300]: Since you did the new conversion above, is the `/ 1000000000.0` division still necessary?

**Comment by odormond** [comment]
> > the value of mach_timebase_info should be cached somewhere
> 
> Makes sense. You can do that in `psutil_setup()` function, which is called on module init:
> 
> https://github.com/giampaolo/psutil/blob/8fa1746685a86b8ddda454e2e2746d535e2b6d89/psutil/_psutil_common.c#L395
> 
> You should define the new global var as a C `extern` defined in `_psutil_common.h`. grep for `PSUTIL_SYSTEM_INFO` to see how it's done.

Sure. I just pushed another commit doing just that. If it's good for you I can squash it to replace the previous two.

About the division by a billion, the mach_timebase_info give the conversion ratio from ticks to nanoseconds so the result still needs to be converted to seconds.

File: psutil/_psutil_common.c [hunk 2]
```diff
@@ -170,6 +170,15 @@ convert_kvm_err(const char *syscall, char *errbuf) {
...
 
+// ====================================================================
+// --- macOS
+// ====================================================================
+
+#ifdef PSUTIL_OSX
+#include <mach/mach_time.h>
+
+struct mach_timebase_info MACH_TIMEBASE_INFO;
+#endif
```
Comment (giampaolo) [inline psutil/_psutil_common.c:181]: In order to be consistent with `PSUTIL_SYSTEM_INFO`, `PSUTIL_CRITICAL_SECTION` and `PSUTIL_DEBUG` I suggest to:

* call this `PSUTIL_MACH_TIMEBASE_INFO`
* define it in `_psutil_common.h` file

File: psutil/_psutil_common.c [hunk 3]
```diff
@@ -405,5 +414,9 @@ psutil_setup(void) {
     InitializeCriticalSection(&PSUTIL_CRITICAL_SECTION);
 #endif
 
+#ifdef PSUTIL_OSX
+    mach_timebase_info(&MACH_TIMEBASE_INFO);
+#endif
```
Comment (giampaolo) [inline psutil/_psutil_common.c:419]: I would invoke this from `psutil_setup()` function instead, so that all init functions are in the same place.

File: psutil/_psutil_osx.c [hunk 4]
```diff
@@ -279,16 +279,22 @@ static PyObject *
 psutil_proc_pidtaskinfo_oneshot(PyObject *self, PyObject *args) {
     pid_t pid;
     struct proc_taskinfo pti;
+    uint64_t total_user, total_system;
```
Comment (giampaolo) [inline psutil/_psutil_osx.c:282]: one declaration per line

**Review by giampaolo — CHANGES_REQUESTED** [review]

File: psutil/_psutil_common.c (hunk 2 above)
Comment (odormond) [reply psutil/_psutil_common.c:181]: > In order to be consistent with `PSUTIL_SYSTEM_INFO`, `PSUTIL_CRITICAL_SECTION` and `PSUTIL_DEBUG` I suggest to:
> 
>     * call this `PSUTIL_MACH_TIMEBASE_INFO`

That makes more sense indeed. Sorry.

>     * define it in `_psutil_common.h` file

I don't understand this. The header file does have the extern definition and storage can only be in the .c file. What am I missing?

File: psutil/_psutil_common.c (hunk 3 above)
Comment (odormond) [reply psutil/_psutil_common.c:419]: It is. Do you prefer that I move it before the Windows conditional block?

File: psutil/_psutil_osx.c (hunk 1 above)
Comment (odormond) [reply psutil/_psutil_osx.c:298]: Yes. The mach timebase conversion ratio produces nanoseconds.

File: psutil/_psutil_common.c (hunk 3 above)
Comment (giampaolo) [reply psutil/_psutil_common.c:419]: Oh didn't realize you were already in psutil_setup() function, sorry

**Comment by giampaolo** [comment]
Merged. Thanks!
